#!/usr/bin/env bash

script_dir="$(dirname "$0")"

default="$script_dir/../img.jpg"

img="${1:-"$default"}"

mkdir -p /tmp/didder_tests

count=0
while read p; do
  echo "didder --palette \"black white\" -i $img -o /tmp/didder_tests/out_$count.png $p"
  echo "didder --palette \"black white\" -i $img -o /tmp/didder_tests/out_$count.png $p"|bash
  (( count++ ))
done <$script_dir/../didders

echo "styles generated in /tmp/didder_tests"
